# Generated by Django 4.1.2 on 2025-03-20 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ResidentManagement', '0002_detectedface'),
        ('UserPortal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('clearance', 'Barangay Clearance'), ('indigency', 'Certificate of Indigency'), ('business', 'Business Permit'), ('building', 'Building Permit'), ('residency', 'Certificate of Residency')], max_length=20)),
                ('request_id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResidentManagement.residentsinfo')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
