# Generated by Django 4.1.2 on 2025-03-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearance',
            name='support_document',
            field=models.FileField(blank=True, null=True, upload_to='clearance_documents/'),
        ),
    ]
