# Generated by Django 4.1.2 on 2025-03-27 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0005_remove_clearance_support_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndigencyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='indigency_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('indigency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='UserPortal.certificateofindigency')),
            ],
        ),
    ]
