# Generated by Django 4.1.2 on 2025-03-27 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0007_businessdocument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessdocument',
            old_name='business',
            new_name='business_permit',
        ),
    ]
