# Generated by Django 4.1.2 on 2025-03-27 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0008_rename_business_to_business_permit'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='building_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('building_permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='UserPortal.buildingpermit')),
            ],
        ),
    ]
