# Generated by Django 4.1.2 on 2025-03-27 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0009_buildingdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidencyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='residency_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('residency_certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='UserPortal.residencycertificate')),
            ],
        ),
    ]
