# Generated by Django 4.1.2 on 2025-03-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnnouncementManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='announcement-documents'),
        ),
    ]
